### PR TITLE
Add Rake Tasks Section

### PR DESCRIPTION
**Pull request by halogenandtoast**
Add a section describing best practices for Rake tasks

### CODE REVIEW

**Comment by Knack** [comment]
This is a good advice, but... what alternative would you suggest? For example, to put the methods inside a module or a class? 🤔

**Comment by balvig** [comment]
@knack that's the idea I believe. Move as much logic as possible inside classes so that the rake task merely calls "run" on those. Might be nice to add an example to the guides?

**Comment by Knack** [comment]
> Might be nice to add an example to the guides?

That's the point (and sorry for my rhetorical question) :wink:

**Comment by balvig** [comment]
Be the change you want to see in the world 😉

**Pull request merged**
